name: Snake Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test runner
        run: |
          echo "Runner funcionando"
          echo "Sistema: $RUNNER_OS"
          echo "Runner: $RUNNER_NAME"
